# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import liquidity_pb2 as liquidity__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in liquidity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LiquidityCheckServiceStub(object):
    """LiquidityCheckService provides liquidity prediction for banks
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckLiquidity = channel.unary_unary(
                '/liquidity.LiquidityCheckService/CheckLiquidity',
                request_serializer=liquidity__pb2.LiquidityCheckRequest.SerializeToString,
                response_deserializer=liquidity__pb2.LiquidityCheckResponse.FromString,
                _registered_method=True)
        self.GetBalances = channel.unary_unary(
                '/liquidity.LiquidityCheckService/GetBalances',
                request_serializer=liquidity__pb2.GetBalancesRequest.SerializeToString,
                response_deserializer=liquidity__pb2.GetBalancesResponse.FromString,
                _registered_method=True)


class LiquidityCheckServiceServicer(object):
    """LiquidityCheckService provides liquidity prediction for banks
    """

    def CheckLiquidity(self, request, context):
        """CheckLiquidity validates if a bank has sufficient funds for a transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalances(self, request, context):
        """GetBalances returns the current balances for all banks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LiquidityCheckServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckLiquidity': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckLiquidity,
                    request_deserializer=liquidity__pb2.LiquidityCheckRequest.FromString,
                    response_serializer=liquidity__pb2.LiquidityCheckResponse.SerializeToString,
            ),
            'GetBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalances,
                    request_deserializer=liquidity__pb2.GetBalancesRequest.FromString,
                    response_serializer=liquidity__pb2.GetBalancesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'liquidity.LiquidityCheckService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('liquidity.LiquidityCheckService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LiquidityCheckService(object):
    """LiquidityCheckService provides liquidity prediction for banks
    """

    @staticmethod
    def CheckLiquidity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liquidity.LiquidityCheckService/CheckLiquidity',
            liquidity__pb2.LiquidityCheckRequest.SerializeToString,
            liquidity__pb2.LiquidityCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liquidity.LiquidityCheckService/GetBalances',
            liquidity__pb2.GetBalancesRequest.SerializeToString,
            liquidity__pb2.GetBalancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
