# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: liquidity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'liquidity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fliquidity.proto\x12\tliquidity\"V\n\x15LiquidityCheckRequest\x12\x0f\n\x07\x62\x61nk_id\x18\x01 \x01(\t\x12\x1a\n\x12transaction_amount\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\"p\n\x16LiquidityCheckResponse\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x19\n\x11\x61vailable_balance\x18\x02 \x01(\x01\x12\x12\n\nerror_code\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\"\x14\n\x12GetBalancesRequest\"?\n\x13GetBalancesResponse\x12(\n\x08\x62\x61lances\x18\x01 \x03(\x0b\x32\x16.liquidity.BankBalance\"A\n\x0b\x42\x61nkBalance\x12\x0f\n\x07\x62\x61nk_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t2\xbc\x01\n\x15LiquidityCheckService\x12U\n\x0e\x43heckLiquidity\x12 .liquidity.LiquidityCheckRequest\x1a!.liquidity.LiquidityCheckResponse\x12L\n\x0bGetBalances\x12\x1d.liquidity.GetBalancesRequest\x1a\x1e.liquidity.GetBalancesResponseB$Z\"github.com/paynet/nexus-lite/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'liquidity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"github.com/paynet/nexus-lite/proto'
  _globals['_LIQUIDITYCHECKREQUEST']._serialized_start=30
  _globals['_LIQUIDITYCHECKREQUEST']._serialized_end=116
  _globals['_LIQUIDITYCHECKRESPONSE']._serialized_start=118
  _globals['_LIQUIDITYCHECKRESPONSE']._serialized_end=230
  _globals['_GETBALANCESREQUEST']._serialized_start=232
  _globals['_GETBALANCESREQUEST']._serialized_end=252
  _globals['_GETBALANCESRESPONSE']._serialized_start=254
  _globals['_GETBALANCESRESPONSE']._serialized_end=317
  _globals['_BANKBALANCE']._serialized_start=319
  _globals['_BANKBALANCE']._serialized_end=384
  _globals['_LIQUIDITYCHECKSERVICE']._serialized_start=387
  _globals['_LIQUIDITYCHECKSERVICE']._serialized_end=575
# @@protoc_insertion_point(module_scope)
