// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: liquidity.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LiquidityCheckService_CheckLiquidity_FullMethodName = "/liquidity.LiquidityCheckService/CheckLiquidity"
)

// LiquidityCheckServiceClient is the client API for LiquidityCheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiquidityCheckServiceClient interface {
	CheckLiquidity(ctx context.Context, in *LiquidityCheckRequest, opts ...grpc.CallOption) (*LiquidityCheckResponse, error)
}

type liquidityCheckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLiquidityCheckServiceClient(cc grpc.ClientConnInterface) LiquidityCheckServiceClient {
	return &liquidityCheckServiceClient{cc}
}

func (c *liquidityCheckServiceClient) CheckLiquidity(ctx context.Context, in *LiquidityCheckRequest, opts ...grpc.CallOption) (*LiquidityCheckResponse, error) {
	cOpts := append([]grpc.CallOption{}, opts...)
	out := new(LiquidityCheckResponse)
	err := c.cc.Invoke(ctx, LiquidityCheckService_CheckLiquidity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiquidityCheckServiceServer is the server API for LiquidityCheckService service.
// All implementations must embed UnimplementedLiquidityCheckServiceServer
// for forward compatibility
type LiquidityCheckServiceServer interface {
	CheckLiquidity(context.Context, *LiquidityCheckRequest) (*LiquidityCheckResponse, error)
	mustEmbedUnimplementedLiquidityCheckServiceServer()
}

// UnimplementedLiquidityCheckServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLiquidityCheckServiceServer struct {
}

func (UnimplementedLiquidityCheckServiceServer) CheckLiquidity(context.Context, *LiquidityCheckRequest) (*LiquidityCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckLiquidity not implemented")
}
func (UnimplementedLiquidityCheckServiceServer) mustEmbedUnimplementedLiquidityCheckServiceServer() {}

// UnsafeLiquidityCheckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiquidityCheckServiceServer will
// result in compilation errors.
type UnsafeLiquidityCheckServiceServer interface {
	mustEmbedUnimplementedLiquidityCheckServiceServer()
}

func RegisterLiquidityCheckServiceServer(s grpc.ServiceRegistrar, srv LiquidityCheckServiceServer) {
	s.RegisterService(&LiquidityCheckService_ServiceDesc, srv)
}

func _LiquidityCheckService_CheckLiquidity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiquidityCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquidityCheckServiceServer).CheckLiquidity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiquidityCheckService_CheckLiquidity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquidityCheckServiceServer).CheckLiquidity(ctx, req.(*LiquidityCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LiquidityCheckService_ServiceDesc is the grpc.ServiceDesc for LiquidityCheckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a partial copy).
var LiquidityCheckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liquidity.LiquidityCheckService",
	HandlerType: (*LiquidityCheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckLiquidity",
			Handler:    _LiquidityCheckService_CheckLiquidity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "liquidity.proto",
}
